title:     Spurthy M
logo: assets/img.jpg
description: > # your text below (remove <br> elements if you don't need line breaks)
 
  Actively looking for Full-Time Opportunities.
  <br>
 <a href="https://www.linkedin.com/in/spurthym/">LinkedIn</a> 
   <br>
  
  <a href="https://github.com/spurthy99">Github</a> 
   <br>
  <a "https://github.com/spurthy99/Resume/blob/main/Spurthy_Resume_DE.pdf">Resume</a> 
  
theme: jekyll-theme-minimal
