title: Spurthy M
logo: assets/img.jpg
description: >
  <br><br>
  Actively looking for Full-Time Opportunities.
  <br><br>
  <a href="https://www.linkedin.com/in/spurthym/">LinkedIn</a> 
  <br><br>
  <a href="https://github.com/spurthy99">Github</a> 
  <br><br>
  <a href="https://github.com/spurthy99/Resume/blob/main/Spurthy_Resume_DE.pdf">Resume</a> 

theme: jekyll-theme-minimal
